#!/bin/sh

set -o noclobber
set -o nounset
set -o errexit

# physically move messages to appropriate IMAP folders, based on notmuch ±tags
# (needed to have correct views in the Gmail apps)

d="$(dirname "$(readlink -f "$0")")"
maildir="$(notmuch config get database.path)"

# See http://cr.yp.to/proto/maildir.html for maildir naming schemes
pid="$$"
increment="$(mktemp)"
hostname="$(hostname)"
rm "$increment" && echo 1 >"$increment"

grep_escape='s/(\^|\$|\[|\]|\*|\.|\\)/\\\1/g'

new_name(){
    local flags="$(basename "$1" | grep -o ':.*$')"
    local incr="$(cat "$increment")"
    rm "$increment" && echo "$(( $incr + 1 ))" >"$increment"
    echo "$(date '+%s').${pid}_${incr}.${hostname}${flags}"
}

to(){
    local dest="$1"
    local mode="$2"
    local query="$3"

    local dest_regex="^$(echo "$maildir/$dest/" | sed -re 's/\/+/\//g' | sed -re "$grep_escape")"

    notmuch search --output=messages "$query" | while IFS= read -r id ; do
        local files="$(notmuch search --output=files "$id")"
        if [ -n "$files" ] ; then # to check for some notmuch anomaly :O
            # it is possible, that this exact message already exists in
            # $dest. If so, don’t put another copy there.
            dest_file="$(echo "$files" | grep "$dest_regex")" || true
            if [ -z "$dest_file" -o '!' '(' -n "$dest_file" -a -e "$dest_file" ')' ] ; then
                # if it’s not in $dest yet…
                echo "###${dest_file}###"
                echo "###${files}###"
                src="$(echo "$files" | head -n 1)"
                dest_file="$maildir/$dest/cur/$(new_name "$src")"
                [ "$mode" = "move" ] && local cmd=mv || local cmd=cp
                echo "$cmd" -v "$src" "$dest_file" || true
                "$cmd" -v "$src" "$dest_file" || true
            fi

            if [ "$mode" = "move" -a -e "$dest_file" ] ; then
                # if this is a move, remove the message from other locations; if copy, ignore them
                echo "$files" | grep -v "$dest_regex" | xargs rm -v || true # some file might already not exist there
            fi
        fi
    done
    
    "$d"/notmuch-retrying new
}

# order is important!

# refresh database
"$d"/notmuch-retrying new

# trash:  move undeleted messages back to gmail.inbox or gmail.all-mail; move spam to gmail.spam
to inbox    move 'folder:trash and tag:inbox'
to all-mail move 'folder:trash and (not tag:deleted)'
to spam     move 'folder:trash and tag:spam'

# spam:  same for gmail.spam, but keep deleted messages there (as a training data for their ML algos)
to inbox    move 'folder:spam and tag:inbox'
to all-mail move 'folder:spam and (not tag:spam)'

# inbox:  mark as spam, delete and archive; also move +draft (IMAP +D flag, which Gmail handles *sometimes*) to drafts
to spam     move 'folder:inbox and tag:spam'
to trash    move 'folder:inbox and tag:deleted'
to drafts   move 'folder:inbox and tag:draft'
to all-mail move 'folder:inbox and (not tag:inbox)'

# all-mail:  mark as spam, delete, fix drafts, and move to inbox
to spam     move 'folder:all-mail and tag:spam'
to trash    move 'folder:all-mail and tag:deleted'
to drafts   move 'folder:all-mail and tag:draft and (not folder:drafts)'
to inbox    copy 'folder:all-mail and tag:inbox and (not folder:inbox)'

# remove the increment file
rm "$increment"

# backup spam for future use
"$d"/backup-spam
