#!/bin/sh

set -o noclobber
set -o nounset
set -o errexit

owndir="$(cd -P -- "$(dirname "$0")" ; pwd -P)"

[ "$HOME/.dotfiles/setup" = "$owndir/setup" ] || { echo >&2 "fatal: $0: must be called at $HOME/.dotfiles/" ; exit 1 ; }

baksuffix="$(date +'dotfiles-bak.%Y%m%d-%H%M%S-%N')"

exclude="$HOME/.dotfiles/setup.exclude"
[ -e "$exclude" ] || exclude=""

uname | grep -qi darwin && darwin=1 || darwin=

cd "$HOME/.dotfiles/"
find . -name '*.symlink' | while IFS= read -r src ; do
    nest="$(dirname "$src" | sed -Ee 's/[^\/]//g' | sed -Ee 's/./..\//g')"
    src="$(echo "$src" | sed -Ee 's/^\.\///')"
    dst="$(echo "$src" | sed -Ee 's/\.symlink$//')"

    [ $darwin ]       || echo "$dst" | grep -qv    '^Library/' || continue
    [ -z "$exclude" ] || echo "$dst" | grep -qvxFf "$exclude"  || continue

    dst="$HOME/$dst"
    src="${nest}.dotfiles/$src"

    mkdir -p "$(dirname "$dst")"

    if [ -e "$dst" -a '!' '(' -h "$dst" -a "$(readlink "$dst")" = "$src" ')' ] ; then
        echo "warning: \`$dst' exists and does not symlink to \`$src', backing up."
        mv -v "$dst" "$dst.$baksuffix"
        echo
    fi

    if [ ! -e "$dst" ] ; then
        ln -s "$src" "$dst"
    fi
done

# run `ssh -V' to initially setup `~/.ssh/{config,authorized_hosts}'
"$HOME/.bin/ssh" -V >/dev/null 2>&1 || true

# run setup.local if exists
local="$HOME/.dotfiles/setup.local"
[ -e "$local" ] && exec "$local" || true
