#!/bin/sh

# Keeps xfce4-power-manager alive… For some reason it dies after
# suspend/hibernation.

while true ; do
  # remember that pgrep can only grep for up to 15 chars
  pgrep xfce4-power-man >/dev/null || xfce4-power-manager
  sleep 5
done
