#!/bin/sh

#daemonize=daemonize
#command $daemonize 1>/dev/null 2>&1 || daemonize=exec
daemonize=exec

# NixOS doesn’t respect these…
$daemonize $HOME/.bin/command-p chromium --no-default-browser-check $CHROMIUM_USER_FLAGS "$@"
