#!/bin/sh

[ $# = 1 ] || { echo >&2 "Usage: $0 <image-file>" ; exit 1 ; }

img="$1"
dir="$(dirname "$img")"

[ "$dir" = "." ] && ( echo "$img" | grep -qv '^\./' ) && img="./$img"

exec feh -d -. --start-at "$img" "$dir"
