#!/bin/sh

set -o noclobber
set -o errexit
set -o nounset

mtp_dev="$(gvfs-mount -l | grep -Eo 'mtp://\[[^\]+]/' | sort --unique)"

num_devices="$(echo "$mtp_dev" | wc -l)"
if [ "$num_devices" -ne 1 ] ; then
  echo >&2 "Currently, $num_devices GVFS devices are connected. There has to be exactly 1."
  exit 1
fi;

mtp_root="${mtp_dev}Phone"
local_root="$HOME/Downloads/andro-dload.$(date '+%Y%m%d-%H%M%S')"

echo "Downloading"
echo "  from  \`$mtp_root/'"
echo "  to    \`$local_root/'"

mkdir "$local_root"

gvfs-info "$mtp_root" >/dev/null

cd "/run/user/$EUID/gvfs/"
[ "$(ls | wc -l)" -eq 1 ]  # should not happen
cd "$(ls)/Phone/"

echo "  times \`$(pwd)'"

which cptime >/dev/null

for dir in "DCIM" "Download" "InCallRecorder" "Pictures" "Snapchat" ; do
  find "$dir" -type d -exec mkdir -p "$local_root/{}" ';'
  find "$dir" -type f \
    -exec echo "$mtp_root/{}" ';' \
    -exec gvfs-copy --progress --preserve "$mtp_root/{}" "$local_root/{}" ';' \
    -exec cptime "{}" "$local_root/{}" ';'
done
