#!/bin/sh

set -o noclobber
set -o errexit
set -o nounset

mtp_dev="$(gvfs-mount -l | grep -Eo 'mtp://\[[^\]+]/' | sort --unique)"

num_devices="$(echo "$mtp_dev" | wc -l)"
if [ "$num_devices" -ne 1 ] ; then
  echo >&2 "Currently, $num_devices GVFS devices are connected. There has to be exactly 1."
  exit 1
fi;

mtp_root="${mtp_dev}Phone"
local_root="$HOME/Downloads/andro-dload.$(date '+%Y%m%d-%H%M%S')"

echo "Downloading"
echo "  from  \`$mtp_root/'"
echo "  to    \`$local_root/'"

mkdir "$local_root"

gvfs-info "$mtp_root" >/dev/null

cd "/run/user/$EUID/gvfs/"
[ "$(ls | wc -l)" -eq 1 ]  # should not happen
cd "$(ls)/Phone/"

echo "  times \`$(pwd)'"

which cptime >/dev/null

for dir in "DCIM" "Download" "InCallRecorder" "Pictures" "Snapchat" ; do
  find "$dir" -type d -exec mkdir -p "$local_root/{}" ';'
  find "$dir" -type f | while IFS= read -r file ; do
    echo "$mtp_root/$file"
    urlencoded="$(printf "$file" | perl -pe 's/([^a-zA-Z0-9\/_.-])/sprintf("%%%02X", ord($1))/ge')"
    gvfs-copy --progress --preserve "$mtp_root/$urlencoded" "$local_root/$file"
    cptime "$file" "$local_root/$file"
  done
done

cd "$local_root"

find -type d -exec chmod 700 '{}' ';'
find -type f -exec chmod 600 '{}' ';'

find 'DCIM/Camera' -name '*_*.jpg' -exec j my '{}' ';'
find 'DCIM/Camera' -name '*.exv' -exec rm '{}' ';'
find 'DCIM/Camera' -name '*.mp4' -exec ren '{}' ';'

find 'Snapchat' -name 'Snapchat-*.*' -exec ren '{}' ';'

find 'Pictures' '(' -name '*.jpg' -o -name '*.jpeg' -o -name '*.png' ')' -exec ren '{}' ';'
