#!/usr/bin/perl

use strict;
use warnings;
use utf8;
use Encode;
use LWP::Simple qw(get);

binmode(STDOUT, ":utf8");
binmode(STDERR, ":utf8");
binmode(STDIN,  ":utf8");

sub babla {
  my $text = get("http://en.bab.la/dictionary/polish-english/" . shift);
  $text =~ s/^.*<h4><i class="icon-chevron-right"><\/i>Summary<\/h4>(.*?)<h4><i class="icon-chevron-right"><\/i>Synonyms<\/h4>.*$/$1/gis;
  $text =~ s/<br>/ — /gis;
  $text =~ s/<.*?>/ /gis;
  $text =~ s/&nbsp;?/ /gis;
  $text =~ s/^\s+|\s+$//gis;
  $text =~ s/\s+/ /gis;
  $text =~ s/\s+full\s+details$//gis;
  return $text;
}

if (scalar(@ARGV) > 0) {
  print babla(join(" ", map { Encode::_utf8_on($_); $_ } @ARGV)) . "\n";
} else {
  print babla($_) while (<>);
}
