#!/bin/sh

if [ "$1" == "pull" ] ; then
  echo 'git: '\''pull'\'' is deliberately disabled.'
  echo
  echo 'Merge/rebase manually after issuing:'
  echo '	git fetch'
  exit 1
else
  exec /usr/bin/git "$@"
fi
