#!/bin/sh

set -o noclobber
set -o errexit
set -o nounset

[ -n "$(git status --porcelain)" ] && { echo >&2 "error: working directory not clean, exiting" ; exit 1 ; }

git checkout master

git fetch --all

git merge --ff-only

git branch --merged=master | grep -Ev '^\* | master$' | sed -re 's/^\s+|\s+$//g' | while IFS= read -r branch ; do
  git push origin ":$branch" || true
  git branch -d "$branch"
done
