#!/bin/sh

function die () {
  echo "$@" >&2
  exit -1
}

[ $# -eq 5 ] || die "Usage: $0 <url> <name> <surname> <date> <retry-every-n-sec>"

function nohtml () {
  cat | sed 's/<[^>]\+>/ /g' | sed -r 's/\s+/ /g' | sed -r 's/^\s+|\s+$//g' | grep -v '^$'
}

function curl () {
  local cj=$1 ; shift ; /usr/bin/curl '-#' --fail --location --connect-timeout 5 --cookie "$cj" --cookie-jar "$cj" "$@"
}

function try () {
  [ $# -ne 4 ] && die 'Wtf?'

  echo '——— (re)trying…'

  local ckjar=$(mktemp)
  local token=$(curl "$ckjar" "$1" | grep -E 'name="token"' | grep -Eio '[0-9a-z]{20,}')
  local reslt=$(curl "$ckjar" "$1" --data "name=${2}&surname=${3}&date=${4}&token=${token}" | nohtml | grep -Ei 'zapisan')
  rm "$ckjar"

  echo && [ -n "$reslt" ] && echo "$reslt" && die '——— Success!'
}

while true ; do
  try "$1" "$2" "$3" "$4"
  sleep "$5"
done
