#!/bin/sh

die() {
  echo 'fatal:' "$@" >&2
  exit 1
}

ftar="${HOME}/.mshell.tgz"
floc="${HOME}/.mshell-local"
frem="${HOME}/.mshell-removals"

curl -L -o "$ftar" 'https://michalrus.com/mshell' || die "curl"

echo

tar -xzvf "$ftar" --no-same-owner -C "${HOME}/" || die "tar"

echo
cat "$frem" | while IFS= read -r file ; do
  rm -v "${HOME}/${file}" 2>/dev/null
done

if [ -x "$floc" ] ; then
  echo
  echo "Executing local mods..."
  "$floc" && echo 'done.'
fi
