#!/bin/sh

set -o noclobber
set -o nounset
set -o errexit

# backup spam (for possible future use in learning) (as Gmail deletes spam older than 30 days)
maildir="$(notmuch config get database.path)"
exec rsync -a "$maildir"/spam/. "$maildir"/spam-backup
